// Generated by Haxe 3.4.7
(function ($hx_exports) { "use strict";
$hx_exports["acsv"] = $hx_exports["acsv"] || {};
var StringTools = function() { };
StringTools.replace = function(s,sub,by) {
	return s.split(sub).join(by);
};
var acsv_Field = $hx_exports["acsv"]["Field"] = function() {
};
var acsv_Table = $hx_exports["acsv"]["Table"] = function() {
	this._selected = null;
	this._indexSet = { };
	this.body = [];
	this.head = [];
	this.content = null;
};
acsv_Table.Parse = function(content,filedSeparator,filedMultiLineDelimiter) {
	if(filedMultiLineDelimiter == null) {
		filedMultiLineDelimiter = "\"";
	}
	if(filedSeparator == null) {
		filedSeparator = ",";
	}
	var table = acsv_Table.arrayToRows(acsv_Table.textToArray(content,filedSeparator,filedMultiLineDelimiter));
	table.content = content;
	return table;
};
acsv_Table.textToArray = function(text,FS,FML) {
	if(FML == null) {
		FML = "\"";
	}
	if(FS == null) {
		FS = ",";
	}
	var FMLs = FML + FML;
	var array = [];
	var maxLen = text.length;
	var ptr = text;
	var ptrPos = 0;
	while(true) {
		var curLen = maxLen - ptrPos;
		var cellIndexA = 0;
		var cellIndexB = 0;
		var cells = [];
		var cell;
		var chr;
		while(cellIndexB < curLen) {
			cellIndexA = cellIndexB;
			chr = ptr.charAt(ptrPos + cellIndexB);
			if(chr == "\n" || chr == "\r\n") {
				++cellIndexB;
				break;
			}
			if(chr == "\r" && ptr.charAt(ptrPos + cellIndexB + 1) == "\n") {
				cellIndexB += 2;
				break;
			}
			if(chr == FS) {
				cell = "";
				var nextPos = ptrPos + cellIndexB + 1;
				if(nextPos >= maxLen) {
					chr = "\n";
				} else {
					chr = ptr.charAt(nextPos);
				}
				if(cellIndexA == 0 || chr == FS || chr == "\n" || chr == "\r\n") {
					++cellIndexB;
					cells.push("");
				} else if(chr == "\r" && ptr.charAt(ptrPos + cellIndexB + 2) == "\n") {
					cellIndexB += 2;
					cells.push("");
				} else {
					++cellIndexB;
				}
			} else if(chr == FML) {
				++cellIndexB;
				while(true) {
					cellIndexB = ptr.indexOf(FML,ptrPos + cellIndexB);
					if(cellIndexB == -1) {
						console.log("[ACsv] Invalid Double Quote");
						return null;
					}
					cellIndexB -= ptrPos;
					if(ptr.charAt(ptrPos + cellIndexB + 1) == FML) {
						cellIndexB += 2;
						continue;
					}
					break;
				}
				cell = ptr.substring(ptrPos + cellIndexA + 1,ptrPos + cellIndexB);
				cell = StringTools.replace(cell,FMLs,FML);
				cells.push(cell);
				++cellIndexB;
			} else {
				var indexA = ptr.indexOf(FS,ptrPos + cellIndexB);
				if(indexA == -1) {
					indexA = curLen;
				} else {
					indexA -= ptrPos;
				}
				var indexB = ptr.indexOf("\r\n",ptrPos + cellIndexB);
				if(indexB == -1) {
					indexB = ptr.indexOf("\n",ptrPos + cellIndexB);
					if(indexB == -1) {
						indexB = curLen;
					} else {
						indexB -= ptrPos;
					}
				} else {
					indexB -= ptrPos;
				}
				cellIndexB = indexA;
				if(indexB < indexA) {
					cellIndexB = indexB;
				}
				cell = ptr.substring(ptrPos + cellIndexA,ptrPos + cellIndexB);
				cells.push(cell);
			}
		}
		array.push(cells);
		ptrPos += cellIndexB;
		if(ptrPos >= maxLen) {
			break;
		}
	}
	return array;
};
acsv_Table.arrayToRows = function(array) {
	var head = array.shift();
	var body = array;
	var fileds = [];
	var _g1 = 0;
	var _g = head.length;
	while(_g1 < _g) {
		var i = _g1++;
		var fullName = head[i];
		var parts = fullName.split(":");
		var filed = new acsv_Field();
		filed.fullName = fullName;
		filed.name = parts[0];
		filed.type = parts[1];
		fileds.push(filed);
	}
	var _g11 = 0;
	var _g2 = body.length;
	while(_g11 < _g2) {
		var i1 = _g11++;
		var row = body[i1];
		var _g3 = 0;
		var _g21 = row.length;
		while(_g3 < _g21) {
			var j = _g3++;
			var type = fileds[j].type;
			var cell = row[j];
			var newVal = cell;
			var isEmptyCell = cell == null || cell == "";
			if(type == "bool") {
				if(isEmptyCell || cell == "false" || cell == "0") {
					newVal = false;
				} else {
					newVal = true;
				}
			} else if(type == "int") {
				if(isEmptyCell) {
					newVal = 0;
				} else {
					newVal = parseInt(newVal);
				}
			} else if(type == "number") {
				if(isEmptyCell) {
					newVal = 0.0;
				} else {
					newVal = parseFloat(newVal);
				}
			} else if(type == "json") {
				if(isEmptyCell) {
					newVal = null;
				} else {
					var chr0 = cell.charAt(0);
					if(!(chr0 == "[" || chr0 == "{")) {
						console.log("[ACsv] Invalid json format:" + fileds[j].name + "," + cell);
						return null;
					}
					newVal = cell;
				}
			} else if(type == "strings") {
				if(isEmptyCell) {
					newVal = "[]";
				} else {
					newVal = "[\"" + cell.split(",").join("\",\"") + "\"]";
				}
			}
			row[j] = newVal;
		}
		body[i1] = row;
	}
	var table = new acsv_Table();
	table.head = fileds;
	table.body = body;
	return table;
};
acsv_Table.prototype = {
	merge: function(b) {
		this.body = this.body.concat(b.body);
		var index = b.content.indexOf("\r\n");
		if(index == -1) {
			index = b.content.indexOf("\n");
		}
		var c = b.content.substring(index);
		this.content += c;
	}
	,createIndexAt: function(colIndex) {
		var map = { };
		var _g1 = 0;
		var _g = this.body.length;
		while(_g1 < _g) {
			var i = _g1++;
			var row = this.body[i];
			var key = row[colIndex];
			map[key] = row;
		}
		this._indexSet[colIndex] = map;
	}
	,getColIndexBy: function(name) {
		var _g1 = 0;
		var _g = this.head.length;
		while(_g1 < _g) {
			var i = _g1++;
			var field = this.head[i];
			if(field.name == name) {
				return i;
			}
		}
		return -1;
	}
	,sortBy: function(colIndex,sortType) {
		var len = this._selected.length;
		var _g1 = 0;
		var _g = len;
		while(_g1 < _g) {
			var i = _g1++;
			var _g3 = 0;
			var _g2 = len - 1;
			while(_g3 < _g2) {
				var j = _g3++;
				var ok = false;
				var a = this._selected[j][colIndex];
				var b = this._selected[j + 1][colIndex];
				if(sortType == 0 && a > b) {
					ok = true;
				} else if(sortType == 1 && a < b) {
					ok = true;
				}
				if(ok) {
					var temp = this._selected[j];
					this._selected[j] = this._selected[j + 1];
					this._selected[j + 1] = temp;
				}
			}
		}
		return this;
	}
	,getCurrentSelectdData: function() {
		return this._selected;
	}
	,fmtRow: function(row) {
		var obj = [];
		var _g1 = 0;
		var _g = this.head.length;
		while(_g1 < _g) {
			var i = _g1++;
			var type = this.head[i].type;
			var val0 = row[i];
			var val1 = null;
			if(type != null && type != "" && acsv_Table.JSON_TYPES.indexOf(type) != -1) {
				if(val0 != null) {
					val1 = JSON.parse(val0);
				}
			} else {
				val1 = val0;
			}
			obj.push(val1);
		}
		return obj;
	}
	,fmtObj: function(row) {
		var obj = { };
		var _g1 = 0;
		var _g = this.head.length;
		while(_g1 < _g) {
			var i = _g1++;
			var name = this.head[i].name;
			var type = this.head[i].type;
			var val0 = row[i];
			var val1 = null;
			if(type != null && type != "" && acsv_Table.JSON_TYPES.indexOf(type) != -1) {
				if(val0 != null) {
					val1 = JSON.parse(val0);
				}
			} else {
				val1 = val0;
			}
			obj[name] = val1;
		}
		return obj;
	}
	,toFirstRow: function() {
		var rzl = null;
		if(this._selected != null && this._selected.length > 0) {
			rzl = this.fmtRow(this._selected[0]);
		}
		this._selected = null;
		return rzl;
	}
	,toLastRow: function() {
		var rzl = null;
		if(this._selected != null && this._selected.length > 0) {
			rzl = this.fmtRow(this._selected[this._selected.length - 1]);
		}
		this._selected = null;
		return rzl;
	}
	,toRows: function() {
		if(this._selected == null) {
			return null;
		}
		var dst = [];
		var _g1 = 0;
		var _g = this._selected.length;
		while(_g1 < _g) {
			var i = _g1++;
			var row = this._selected[i];
			dst.push(this.fmtRow(row));
		}
		this._selected = null;
		return dst;
	}
	,toFirstObj: function() {
		var rzl = null;
		if(this._selected != null && this._selected.length > 0) {
			rzl = this.fmtObj(this._selected[0]);
		}
		this._selected = null;
		return rzl;
	}
	,toLastObj: function() {
		var rzl = null;
		if(this._selected != null && this._selected.length > 0) {
			rzl = this.fmtObj(this._selected[this._selected.length - 1]);
		}
		this._selected = null;
		return rzl;
	}
	,toObjs: function() {
		if(this._selected == null) {
			return null;
		}
		var dst = [];
		var _g1 = 0;
		var _g = this._selected.length;
		while(_g1 < _g) {
			var i = _g1++;
			var row = this._selected[i];
			dst.push(this.fmtObj(row));
		}
		this._selected = null;
		return dst;
	}
	,toTable: function() {
		if(this._selected == null) {
			return null;
		}
		var t = new acsv_Table();
		t.head = this.head.concat([]);
		t.body = this._selected;
		this._selected = null;
		return t;
	}
	,selectAll: function() {
		this._selected = this.body;
		return this;
	}
	,selectFirstRow: function() {
		this._selected = [this.body[0]];
		return this;
	}
	,selectLastRow: function() {
		this._selected = [this.body[this.body.length - 1]];
		return this;
	}
	,selectAt: function(rowIndex) {
		var dst = [];
		if(rowIndex >= 0 && rowIndex < this.body.length) {
			dst.push(this.body[rowIndex]);
		}
		this._selected = dst;
		return this;
	}
	,selectWhenIn: function(limit,values,colIndex) {
		if(colIndex == null) {
			colIndex = 0;
		}
		var rows = [];
		var _g1 = 0;
		var _g = values.length;
		while(_g1 < _g) {
			var i = _g1++;
			var value = values[i];
			this.selectWhenE(limit,value,colIndex,rows);
			this._selected = null;
		}
		this._selected = rows;
		return this;
	}
	,selectWhenE: function(limit,value,colIndex,extraSelector) {
		if(colIndex == null) {
			colIndex = 0;
		}
		var dst = extraSelector;
		if(dst == null) {
			dst = [];
		}
		if(limit == 1) {
			var map = this._indexSet[colIndex];
			if(map != null) {
				var val = map[value];
				if(val != null) {
					dst.push(val);
				}
				this._selected = dst;
				return this;
			}
		}
		var src = this._selected;
		if(src == null) {
			src = this.body;
		}
		var _g1 = 0;
		var _g = src.length;
		while(_g1 < _g) {
			var i = _g1++;
			var row = src[i];
			if(row[colIndex] == value) {
				dst.push(row);
				--limit;
				if(limit == 0) {
					break;
				}
			}
		}
		this._selected = dst;
		return this;
	}
	,selectWhenE2: function(limit,value1,value2,colIndex2,colIndex1) {
		if(colIndex1 == null) {
			colIndex1 = 0;
		}
		if(colIndex2 == null) {
			colIndex2 = 1;
		}
		var src = this._selected;
		if(src == null) {
			src = this.body;
		}
		var dst = [];
		var _g1 = 0;
		var _g = src.length;
		while(_g1 < _g) {
			var i = _g1++;
			var row = src[i];
			if(row[colIndex1] == value1 && row[colIndex2] == value2) {
				dst.push(row);
				--limit;
				if(limit == 0) {
					break;
				}
			}
		}
		this._selected = dst;
		return this;
	}
	,selectWhenE3: function(limit,value1,value2,value3,colIndex3,colIndex2,colIndex1) {
		if(colIndex1 == null) {
			colIndex1 = 0;
		}
		if(colIndex2 == null) {
			colIndex2 = 1;
		}
		if(colIndex3 == null) {
			colIndex3 = 2;
		}
		var src = this._selected;
		if(src == null) {
			src = this.body;
		}
		var dst = [];
		var _g1 = 0;
		var _g = src.length;
		while(_g1 < _g) {
			var i = _g1++;
			var row = src[i];
			if(row[colIndex1] == value1 && row[colIndex2] == value2 && row[colIndex3] == value3) {
				dst.push(row);
				--limit;
				if(limit == 0) {
					break;
				}
			}
		}
		this._selected = dst;
		return this;
	}
	,selectWhenG: function(limit,withEqu,value,colIndex) {
		if(colIndex == null) {
			colIndex = 0;
		}
		var src = this._selected;
		if(src == null) {
			src = this.body;
		}
		var dst = [];
		var _g1 = 0;
		var _g = src.length;
		while(_g1 < _g) {
			var i = _g1++;
			var row = src[i];
			var rowVal = row[colIndex];
			if(rowVal > value || withEqu && rowVal == value) {
				dst.push(row);
				--limit;
				if(limit == 0) {
					break;
				}
			}
		}
		this._selected = dst;
		return this;
	}
	,selectWhenL: function(limit,withEqu,value,colIndex) {
		if(colIndex == null) {
			colIndex = 0;
		}
		var src = this._selected;
		if(src == null) {
			src = this.body;
		}
		var dst = [];
		var _g1 = 0;
		var _g = src.length;
		while(_g1 < _g) {
			var i = _g1++;
			var row = src[i];
			var rowVal = row[colIndex];
			if(rowVal < value || withEqu && rowVal == value) {
				dst.push(row);
				--limit;
				if(limit == 0) {
					break;
				}
			}
		}
		this._selected = dst;
		return this;
	}
	,selectWhenGreaterAndLess: function(limit,GWithEqu,LWithEqu,GValue,LValue,colIndex) {
		if(colIndex == null) {
			colIndex = 0;
		}
		var src = this._selected;
		if(src == null) {
			src = this.body;
		}
		var dst = [];
		var _g1 = 0;
		var _g = src.length;
		while(_g1 < _g) {
			var i = _g1++;
			var row = src[i];
			var rowVal = row[colIndex];
			var v1 = rowVal > GValue || GWithEqu && rowVal == GValue;
			var v2 = rowVal < LValue || LWithEqu && rowVal == LValue;
			if(v1 && v2) {
				dst.push(row);
				--limit;
				if(limit == 0) {
					break;
				}
			}
		}
		this._selected = dst;
		return this;
	}
	,selectWhenLessOrGreater: function(limit,LWithEqu,GWithEqu,LValue,GValue,colIndex) {
		if(colIndex == null) {
			colIndex = 0;
		}
		var src = this._selected;
		if(src == null) {
			src = this.body;
		}
		var dst = [];
		var _g1 = 0;
		var _g = src.length;
		while(_g1 < _g) {
			var i = _g1++;
			var row = src[i];
			var rowVal = row[colIndex];
			var v1 = rowVal < LValue || LWithEqu && rowVal == LValue;
			var v2 = rowVal > GValue || GWithEqu && rowVal == GValue;
			if(v1 || v2) {
				dst.push(row);
				--limit;
				if(limit == 0) {
					break;
				}
			}
		}
		this._selected = dst;
		return this;
	}
};
acsv_Table.JSON_TYPES = ["json","strings"];
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);
